services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=trip_planner

  web:
    build: ./trip_planner
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./trip_planner:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn trip_planner.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: