services:
  web:
    build: ./trip_planner
    restart: always
    volumes:
      - ./trip_planner:/app
      - ./trip_planner/data:/app/data
      - ./media:/app/media  # Use a local directory for media files
      - ./.env:/app/.env
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - DEBUG=1
      - SECRET_KEY=XX2hByOdctNWDJ0WNA_fuVNC9kBT26MTBtsU_xvQbsCrVic9cdEj9sfhiK2xQr3nPlo
      - DJANGO_ALLOWED_HOSTS=*
      - SQL_ENGINE=django.db.backends.sqlite3
      - SQL_DATABASE=/app/data/db.sqlite3
    command: >
      sh -c "pip install debugpy && 
        cd /app &&
        python -m debugpy --listen 0.0.0.0:3001 --wait-for-client manage.py runserver 0.0.0.0:8000 --noreload"